begin;

-- Seeded from resin-data.js and the existing resin-description-info.js lookup
-- rules. NULL means the current application has no value for that field.
insert into public.resins (resin_code, display_description, density_g_cm3, information_description, is_active)
values
  ('00328 nexxstar', NULL, 0.928, NULL, true),
  ('1018', NULL, 0.918, NULL, true),
  ('1018 exceed', NULL, 0.918, NULL, true),
  ('1122', NULL, 0.920, NULL, true),
  ('40-02 enable', NULL, 0.940, NULL, true),
  ('41e710 Bynel', NULL, 0.924, NULL, true),
  ('5940', NULL, 0.940, NULL, true),
  ('6410', NULL, 0.959, NULL, true),
  ('7120', NULL, 0.919, NULL, true),
  ('760', NULL, 0.930, NULL, true),
  ('9659HD', NULL, 0.962, NULL, true),
  ('A0100', 'UVI', 0.949, 'UVI is an additive package that helps protect plastic from degradation caused by ultraviolet (UV) sunlight. It extends outdoor service life by reducing discoloration, brittleness, cracking, and loss of mechanical properties.', true),
  ('A01010', 'CLR10227', 1.100, 'CLR10227 is a volatile corrosion inhibitor (VCI) additive. It slowly releases corrosion-inhibiting molecules that form a protective layer on metal surfaces inside the package, helping prevent rust and corrosion during storage and shipment without leaving a heavy residue.', true),
  ('A0110', 'UVI', 0.957, 'UVI is an additive package that helps protect plastic from degradation caused by ultraviolet (UV) sunlight. It extends outdoor service life by reducing discoloration, brittleness, cracking, and loss of mechanical properties.', true),
  ('A01406', 'Bio Degradable', 0.886, NULL, true),
  ('A0300', '5% Oleamide Slip', 0.915, 'Slip additives lower surface friction and help film move across equipment or against other film surfaces. They can improve winding, converting, and package-opening performance.', true),
  ('A0301', 'SLIP', 0.920, 'Slip additives lower surface friction and help film move across equipment or against other film surfaces. They can improve winding, converting, and package-opening performance.', true),
  ('A0401', '3% Viten', 0.935, 'Slip additives lower surface friction and help film move across equipment or against other film surfaces. They can improve winding, converting, and package-opening performance.', true),
  ('A0425', '3% Flouropolymer', 0.930, 'Process aids improve polymer flow and processing behavior. Depending on the formulation, they may reduce melt fracture, die buildup, and visible surface defects.', true),
  ('A0450', NULL, 0.935, 'A0450 is a polymer processing aid designed to improve resin flow through the extruder and die. It helps reduce melt fracture, die buildup, and surface defects while improving processing stability and allowing smoother operation at higher output rates.', true),
  ('A0500', '80% Calcium Carbonat', 1.950, 'Calcium carbonate is a mineral filler commonly added to polyethylene to reduce cost and modify film properties. It increases stiffness and opacity and can improve handling, but excessive amounts may make the film less flexible and more prone to tearing.', true),
  ('A0502', 'Calcium Carbonate', NULL, 'Calcium carbonate is a mineral filler commonly added to polyethylene to reduce cost and modify film properties. It increases stiffness and opacity and can improve handling, but excessive amounts may make the film less flexible and more prone to tearing.', true),
  ('A0503', 'Calcium Carbonate', NULL, 'Calcium carbonate is a mineral filler commonly added to polyethylene to reduce cost and modify film properties. It increases stiffness and opacity and can improve handling, but excessive amounts may make the film less flexible and more prone to tearing.', true),
  ('A0600', '10% GMS Anti Stat', 0.923, 'Anti-static resins contain additives that reduce the buildup of static electricity on the film surface. This helps minimize dust attraction, improves material handling, and reduces problems caused by electrostatic discharge during processing and packaging.', true),
  ('A0601', 'Ethoxylated Amine', 0.978, 'Anti-static resins contain additives that reduce the buildup of static electricity on the film surface. This helps minimize dust attraction, improves material handling, and reduces problems caused by electrostatic discharge during processing and packaging.', true),
  ('A0605', 'Anti Stat', 0.953, 'Anti-static resins contain additives that reduce the buildup of static electricity on the film surface. This helps minimize dust attraction, improves material handling, and reduces problems caused by electrostatic discharge during processing and packaging.', true),
  ('A0700', 'Anti Block', 1.230, 'Anti-block additives help prevent film layers from sticking together by creating microscopic surface roughness. This improves film opening, handling, and unwind performance.', true),
  ('A0710', 'High Clarity A/B', 0.961, 'Anti-block additives help prevent film layers from sticking together by creating microscopic surface roughness. This improves film opening, handling, and unwind performance.', true),
  ('A0711', NULL, 0.930, NULL, true),
  ('A0720', '50% DE, AB 5% A/S', 1.090, NULL, true),
  ('A0735', NULL, 0.960, NULL, true),
  ('A0750', NULL, 1.380, NULL, true),
  ('A0928', 'Flame Retardant', 1.630, 'Flame retardants are added to polyolefins, polycarbonate, polyamides, polyester, and other polymers to increase resistance to ignition, reduce flame spread, suppress smoke formation, and prevent a polymer from dripping.', true),
  ('A0935', 'Anti Microbial', 1.140, NULL, true),
  ('A1010', 'CLR10227', 1.050, 'CLR10227 is a volatile corrosion inhibitor (VCI) additive. It slowly releases corrosion-inhibiting molecules that form a protective layer on metal surfaces inside the package, helping prevent rust and corrosion during storage and shipment without leaving a heavy residue.', true),
  ('A1408', 'TEST', 1.160, NULL, true),
  ('A1901', NULL, 0.950, 'A1901 is an anti-pinkening additive used to reduce or prevent pink discoloration that can develop in certain polyethylene films during processing, storage, or exposure to environmental conditions. It helps maintain the film''s intended appearance and color consistency.', true),
  ('A2000', NULL, NULL, NULL, true),
  ('AO-TRIAL', NULL, 0.918, NULL, true),
  ('ccblack02', 'General Purpose', 1.230, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccblack05', 'Boot Film Black', 0.950, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccblack06', 'Mulch Black', 1.220, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('CCBLACK07', 'TPM1107', 1.230, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('CCBLACK08', NULL, 1.150, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccblack09', NULL, 1.136, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccblue02', 'Boot Film Blue', 1.400, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccblue05', 'Pond Guard Blue', 1.949, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccblue07', 'Transhield Blue', 1.020, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccblue09', 'Transhield Blue', 1.050, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccbuff02', 'Buff', 1.820, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccgreen02', 'Direct Pkg. Green', 1.370, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccgreen05', 'Reef Green', 1.140, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccgreen06', 'Reef Green', 1.267, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccgreen09', 'Transhield Green', 1.496, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccgreen10', 'Carpenter Green', 1.570, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccgreen11', 'Kingsdown', 1.832, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccgreen15', 'Transhield', 1.140, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('CCGREEN22', NULL, 1.390, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccgrey01', 'Direct Pkg. Grey', 1.770, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccgrey03', 'Direct Pkg. Grey', 1.812, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccgrey04', NULL, 1.580, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccorange01', 'Reef Orange', 1.170, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccorange04', 'Direct Pkg. Orange', NULL, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccorange05', 'Reef Economy Orange', 1.550, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccred03', 'Reef Red', 1.430, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccred05', 'Reef [unknown] Red', 1.440, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccred06', 'Transhield', 1.020, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccsilver02', 'March Silver', 1.284, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('cctan02', 'Transhield', 1.200, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('cctan03', 'Transhield', 1.510, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('cctan04', 'Transhield', NULL, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('cctan05', 'Transhield', 1.500, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('CC-TRIAL', NULL, 0.918, NULL, true),
  ('ccwhite02', 'Mulch White', 1.906, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccwhite04', 'Standard White', NULL, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccwhite07', 'Transhield', 1.980, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccwhite11', 'Direct Pkg Laminati', 2.024, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccwhite13', 'Reef Permalon', 2.037, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccwhite14', NULL, 0.920, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccyellow01', 'Reef Yellow', 1.531, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('ccyellow02', 'Reef Economy Yellow', 1.698, 'Color additives in blown film extrusion provide visual identity, opacity, and UV protection, relying heavily on masterbatches or pigments like titanium dioxide.', true),
  ('D139', NULL, 0.918, NULL, true),
  ('D350', NULL, 0.933, NULL, true),
  ('ELITE 6900', NULL, 0.969, NULL, true),
  ('ENABLE 2703', NULL, 0.927, NULL, true),
  ('Erema', 'Repro', 0.949, NULL, true),
  ('exact 3132', NULL, 0.900, NULL, true),
  ('EXCEED 1018', NULL, 0.923, NULL, true),
  ('EXCEED 1023J', NULL, 0.923, NULL, true),
  ('EXCEED 1327', NULL, 0.927, NULL, true),
  ('EXXON LD105.30', NULL, 0.923, NULL, true),
  ('HD7845', NULL, 0.968, NULL, true),
  ('LD165', NULL, 0.922, NULL, true),
  ('LD317', NULL, 0.926, NULL, true),
  ('MS0100', 'Clarity LDPE', 0.924, 'Low-density polyethylene is flexible, easy to process, and commonly used for film and sealing layers. It also offers good clarity and melt strength in many extrusion applications.', true),
  ('MS0101', 'Clarity LDPE', 0.925, 'Low-density polyethylene is flexible, easy to process, and commonly used for film and sealing layers. It also offers good clarity and melt strength in many extrusion applications.', true),
  ('MS0120', NULL, 0.923, NULL, true),
  ('MS0200', 'Frac Melt', 0.919, NULL, true),
  ('MS0300', 'Super Hexene', 0.917, 'Hexene LLDPE is a linear low-density polyethylene made using hexene as the comonomer. Compared to butene LLDPE, it generally provides higher strength, better puncture and tear resistance, improved toughness, and better performance in demanding film applications.', true),
  ('MS0400', 'Hexene', 0.917, 'Hexene LLDPE is a linear low-density polyethylene made using hexene as the comonomer. Compared to butene LLDPE, it generally provides higher strength, better puncture and tear resistance, improved toughness, and better performance in demanding film applications.', true),
  ('MS0440', 'Med. Density Hexene', 0.926, 'Hexene LLDPE is a linear low-density polyethylene made using hexene as the comonomer. Compared to butene LLDPE, it generally provides higher strength, better puncture and tear resistance, improved toughness, and better performance in demanding film applications.', true),
  ('MS0700', 'MI/MN HDPE', 0.948, 'High-density polyethylene is generally stiffer and denser than LDPE or LLDPE. It commonly provides improved moisture-barrier performance and strength, with less flexibility.', true),
  ('MS0700B', 'Blending HDPE', 0.949, 'High-density polyethylene is generally stiffer and denser than LDPE or LLDPE. It commonly provides improved moisture-barrier performance and strength, with less flexibility.', true),
  ('MS0991', NULL, 0.920, NULL, true),
  ('MS1100', 'Butene', 0.918, 'Butene LLDPE is a linear low-density polyethylene made using butene as the comonomer. It offers good strength, flexibility, and processability while typically costing less than hexene grades. It is commonly used in general-purpose blown film applications.', true),
  ('MS1200', NULL, 0.918, NULL, true),
  ('MS1201', 'Metallocene', 0.912, 'Metallocene polyethylene is produced using metallocene catalysts, creating a more uniform polymer structure. It provides excellent toughness, puncture resistance, seal strength, and clarity, allowing thinner films while maintaining performance.', true),
  ('MS1202', 'Metallocene', 0.915, 'Metallocene polyethylene is produced using metallocene catalysts, creating a more uniform polymer structure. It provides excellent toughness, puncture resistance, seal strength, and clarity, allowing thinner films while maintaining performance.', true),
  ('MS1230', NULL, NULL, NULL, true),
  ('MS1255', NULL, NULL, NULL, true),
  ('MS1290', 'O/G Metallocene', 0.912, 'Metallocene polyethylene is produced using metallocene catalysts, creating a more uniform polymer structure. It provides excellent toughness, puncture resistance, seal strength, and clarity, allowing thinner films while maintaining performance.', true),
  ('MS1307', '6% EVA', 0.926, 'Ethylene-vinyl acetate is commonly used to improve softness, flexibility, sealing performance, and impact resistance. Its behavior varies with vinyl-acetate content and blend level.', true),
  ('MS1318', NULL, 0.947, NULL, true),
  ('MS1400', 'Octene', 0.920, NULL, true),
  ('MS1500', 'Co Polymer', 0.900, NULL, true),
  ('MS3003', NULL, 1.130, NULL, true),
  ('MS5000', 'Elastomer', 0.885, NULL, true),
  ('MS5001', NULL, 0.862, NULL, true),
  ('MS5004', 'Elastomer', 0.874, NULL, true),
  ('MS5005', 'Elastomer', 0.895, NULL, true),
  ('MS5006', NULL, NULL, NULL, true),
  ('MS5009', NULL, NULL, NULL, true),
  ('MS6000', NULL, NULL, NULL, true),
  ('MS6305', 'Micrel 0903', 0.930, NULL, true),
  ('MS6506', 'Ethylene Acrylic Acid I', 0.940, NULL, true),
  ('MS6600', NULL, 0.943, NULL, true),
  ('MSE Trial', NULL, NULL, NULL, true),
  ('NOT USED', NULL, NULL, NULL, true),
  ('papermatch', NULL, 1.720, NULL, true),
  ('PDH087', NULL, 0.900, NULL, true),
  ('ST100', NULL, 0.928, NULL, true),
  ('TEST', NULL, 0.918, NULL, true),
  ('trial process aid 1171', NULL, 0.935, 'Process aids improve polymer flow and processing behavior. Depending on the formulation, they may reduce melt fracture, die buildup, and visible surface defects.', true),
  ('vydyne 8401', NULL, 1.140, NULL, true),
  ('ZIMS EREMA', NULL, 0.996, NULL, true);

commit;
