"use strict";
const test=require("node:test"), assert=require("node:assert/strict"), fs=require("node:fs");
const html=fs.readFileSync("index.html","utf8"), app=fs.readFileSync("app.js","utf8"), css=fs.readFileSync("styles.css","utf8");
test("the standalone Line Configurations panel and its local save/load/export/import controls are gone - shared cloud lists live on in Setup and Recipe Setup instead",()=>{ assert.doesNotMatch(html,/id="recipesBlock"/); assert.doesNotMatch(html,/id="savedConfigs"/); assert.doesNotMatch(html,/id="configName"/); assert.doesNotMatch(html,/id="importJson"/); assert.match(html,/Weight Profiles/); assert.match(html,/id="setupWeightProfilesList"/); assert.match(app,/id="splitsSavedRecipesList"/); });
test("cloud UI uses the service cache and refresh without direct Supabase calls",()=>{ assert.match(app,/workspaceConfigurations\.listReceiverWeightProfiles/); assert.match(app,/workspaceConfigurations\.listRecipes/); assert.match(app,/workspaceConfigurations\.refresh/); assert.doesNotMatch(app,/\.from\("workspace_configurations"\)/); });
test("cloud loads use confirmation dialogs and Phase 1 helpers before one normal sync notification",()=>{ assert.match(html,/workspaceConfigurationLoadDialog/); assert.match(app,/applyRecipePayload/); assert.match(app,/applyReceiverWeightProfile/); assert.match(app,/notifyActiveJobMutation\(\{immediate:true,kind:"load-workspace-configuration"\}\)/); assert.match(app,/receiver hopper weights only/); assert.match(app,/This will change line type/); });
test("workspace switching, cached failure, and narrow layout are handled",()=>{ assert.match(app,/workspaceChanged/); assert.match(app,/workspaceId !== lineSync\?\.getState/); assert.match(app,/Refresh failed; showing cached/); assert.match(css,/workspaceConfigurationRow/); assert.match(css,/@media\(max-width:600px\)/); });
test("shared rows prioritize Load and Update while keeping secondary actions in a keyboard-accessible overflow",()=>{ assert.match(html,/Save Current Weights/); assert.match(app,/Save Current Recipe/); assert.match(html,/Update Existing/); assert.match(html,/Choose Another Name/); assert.match(app,/workspaceConfigurationOverflow/); assert.match(app,/More actions for/); assert.match(app,/actions\.append\(action\("Load"/); assert.match(app,/menuAction\("Rename"/); assert.match(app,/menuAction\("Duplicate"/); assert.match(app,/menuAction\("Delete"/); assert.match(app,/menuAction\(item\.favorite\?"Unfavorite":"Favorite"/); assert.match(css,/workspaceConfigurationOverflowMenu/); });
test("receiver profile overflow menus portal to the viewport outside the transformed sheet",()=>{ assert.match(app,/\.mobileWeightProfilesSheet \.workspaceConfigurationOverflow > summary/); assert.match(app,/document\.body\.append\(popup\)/); assert.match(app,/popup\.style\.position = "fixed"/); assert.match(app,/menu\.append\(popup\)/); });
test("rows are selectable without auto-loading, and the WHOLE row is the hit target",()=>{ assert.match(app,/selectedWorkspaceConfigurationId/); assert.match(app,/row\.tabIndex=0/); assert.match(app,/workspaceConfigurationInfo/);
  // The row's own click handler drives selection; its guard skips only the
  // row's OWN overflow <details> (class .workspaceConfigurationOverflow), not
  // any ancestor <details> (the Recipe panel lives inside #splitsBlock, a
  // <details> - matching a bare "details" there suppressed every row click
  // that was not on the text, so only the text area selected).
  assert.match(app,/row\.addEventListener\("click",event=>\{if\(!event\.target\.closest\("button,summary,\.workspaceConfigurationOverflow"\)\) select\(\);\}\)/);
  assert.doesNotMatch(app,/event\.target\.closest\("button,summary,details"\)/);
  assert.doesNotMatch(app,/info\.addEventListener\("click"/);
  assert.match(app,/row\.classList\.toggle\("selected"/); assert.match(app,/event\.stopPropagation\(\)/); assert.match(css,/workspaceConfigurationRow\.selected/); const desktop=fs.readFileSync("desktop.css","utf8"); assert.match(desktop,/\.workspaceConfigurationRow\.selected\{border:1px solid var\(--focus-border\);background:var\(--focus-ring\);box-shadow:inset 3px 0 0 var\(--focus-border\)\}/);
  // The info block is click-through so the full card is one target...
  assert.match(css,/body\[data-recipe-page="saved"\] #splitsArea > \.splitsSavedRecipesPanel \.workspaceConfigurationRow \.workspaceConfigurationInfo\{[\s\S]*?pointer-events:none;/);
  // ...but the action buttons stay clickable.
  assert.match(css,/body\[data-recipe-page="saved"\] #splitsArea > \.splitsSavedRecipesPanel \.workspaceConfigurationRow \.workspaceConfigurationActions\{[\s\S]*?pointer-events:auto;/);
});
test("favorite semantics and concise metadata are rendered safely",()=>{ assert.match(app,/selectedWorkspace\?\.name/); assert.doesNotMatch(app,/Workspace: \$\{workspaceId/); assert.match(app,/workspaceConfigurationFavorite/); assert.match(app,/Favorite recipe/); assert.match(app,/receiver_weights_lb/); assert.match(app,/assigned hoppers/); });
test("configuration lists cap visible rows and reveal actions only for the selected row (when row actions are enabled - Line Configurations' own lists don't pass showRowActions:false)",()=>{ assert.match(css,/workspaceConfigurationList\{[^}]*max-height:330px[^}]*overflow-y:auto/); assert.match(app,/if\(selected&&showRowActions\)\{const actions=document\.createElement/); assert.match(app,/const selected=selectedWorkspaceConfigurationId===item\.id/); });
